# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GunViolenceArchive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunviolecearchive',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
