# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GunViolenceArchive', '0002_auto_20161113_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunviolecearchive',
            name='civilian_death',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gunviolecearchive',
            name='civilian_injury',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gunviolecearchive',
            name='police_death',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gunviolecearchive',
            name='police_injury',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gunviolecearchive',
            name='shot_dead_by_police',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gunviolecearchive',
            name='is_police_involved',
            field=models.BooleanField(default=False),
        ),
    ]
